# Generated by Django 4.2.4 on 2023-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
