# Generated by Django 4.2.4 on 2023-08-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_orders_customer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, 'IN_CART'), (1, 'CHECKOUT_STARTED'), (2, 'PAYMENT_PENDING'), (3, 'PAYMENT_FAIL'), (4, 'PAYMENT_SUCCESS')], default=0),
        ),
    ]
